language: python
jobs:
  allow_failures:
    - os: osx
    - env: DJANGO_VERSION=3.2
os:
  - linux
  - osx
dist: xenial
env:
  - DJANGO_VERSION=2.2
  - DJANGO_VERSION=3.2
python:
  - '3.7'
  - '3.8'
  - '3.9'
deploy:
  provider: pypi
  username: __token__
  password:
    secure: pypi-AgEIcHlwaS5vcmcCJGUyZTE2ODY0LTFlZDAtNGJjNy1hZTgyLTI4ZTUwMWE3NjAwZQACOnsicGVybWlzc2lvbnMiOiB7InByb2plY3RzIjogWyJkamFuZ28tc3AiXX0sICJ2ZXJzaW9uIjogMX0AAAYgTT9lUx3E5KAlYzDGf-QiWUZy8aENJmURa-HSgsRYdrg
  on:
    tags: true
    repo: DLRSP/django-sp
  skip_cleanup: true
  skip_existing: true
before_install:
  - pip install -r requirements.txt
install:
  - git clone --depth=50 --branch=django-sp https://github.com/DLRSP/example.git DLRSP/example
  - python setup.py install
script:
  - coverage run DLRSP/example/manage.py test --exe --all-modules
  - DLRSP/example/manage.py jenkins --enable-coverage -v 2
after_success:
  - codecov
