# Generated by Django 2.2.24 on 2021-11-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("socialprofile", "0013_auto_20211129_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialprofile",
            name="gender",
            field=models.CharField(
                blank=None,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=10,
                verbose_name="Gender",
            ),
        ),
    ]
